export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
export const SET_ERROR = "SET_ERROR";
export const SET_PAGES = "SET_PAGES";
export const LOAD_MORE_RESULTS = "LOAD_MORE_RESULTS";
export const SET_MOVIE_TYPE = "SET_MOVIE_TYPE";
export const SEARCH_QUERY = "SEARCH_QUERY";
export const SEARCH_RESULT = "SEARCH_RESULT";
